In [23]:
import numpy as np
import pandas as pd

dic = [(10, 'this is a test'),(15, 'how to use word2vec in python'),(20, 'python is cool')]
df = pd.DataFrame(dic, columns=['num','sentence'])
df

num                       sentence
0   10                 this is a test
1   15  how to use word2vec in python
2   20                 python is cool

In [24]:
from gensim.utils import tokenize

df['tokenize'] = df.apply(lambda row: list(tokenize(row['sentence'])), axis=1)
df

num                       sentence                               tokenize
0   10                 this is a test                    [this, is, a, test]
1   15  how to use word2vec in python  [how, to, use, word, vec, in, python]
2   20                 python is cool                     [python, is, cool]

In [29]:
from sklearn.feature_extraction.text import CountVectorizer, TfidfVectorizer

vectorizer = CountVectorizer()
tfidf = TfidfVectorizer()
X = tfidf.fit_transform(df['sentence']).toarray()
X

array([[0.        , 0.        , 0.        , 0.4736296 , 0.        ,
        0.62276601, 0.62276601, 0.        , 0.        , 0.        ],
       [0.        , 0.42339448, 0.42339448, 0.        , 0.32200242,
        0.        , 0.        , 0.42339448, 0.42339448, 0.42339448],
       [0.68091856, 0.        , 0.        , 0.51785612, 0.51785612,
        0.        , 0.        , 0.        , 0.        , 0.        ]])

In [30]:
x = vectorizer.fit_transform(df['sentence']).toarray()
x

array([[0, 0, 0, 1, 0, 1, 1, 0, 0, 0],
       [0, 1, 1, 0, 1, 0, 0, 1, 1, 1],
       [1, 0, 0, 1, 1, 0, 0, 0, 0, 0]], dtype=int64)

In [22]:
model = vectorizer.fit(df['sentence'])
y = model.inverse_transform(x)
y

[array(['is', 'test', 'this'], dtype='<U8'),
 array(['how', 'in', 'python', 'to', 'use', 'word2vec'], dtype='<U8'),
 array(['cool', 'is', 'python'], dtype='<U8')]

In [6]:
import multiprocessing
multiprocessing.cpu_count()

In [32]:
x = np.array([5,1,7,8,2,11])
np.argsort(x)

array([1, 4, 0, 2, 3, 5], dtype=int64)

In [33]:
x.argsort()

array([1, 4, 0, 2, 3, 5], dtype=int64)

In [45]:
from sklearn.metrics.pairwise import linear_kernel
y = X[[0,1],:]
linear_kernel(y,X).argsort()[::-1]

array([[1, 2, 0],
       [0, 2, 1]], dtype=int64)

In [46]:
linear_kernel(y,X).argsort()[::-1]

array([[0, 2, 1],
       [1, 2, 0]], dtype=int64)